### ISSUE TITLE
Add support Laravel 5.6

### ISSUE THREAD

**Issue by mrcage** [dmitry-ivanov/laravel-db-profiler#1]
As Laravel 5.6 has been released, it would be nice to add support for that.

	$ composer update
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.
	
	Problem 1
		- Conclusion: remove illuminated/db-profiler 5.5.4
		- Conclusion: don't install illuminated/db-profiler 5.5.4
		- Conclusion: don't install illuminated/db-profiler 5.5.3
		- Conclusion: don't install illuminated/db-profiler 5.5.2
		- Conclusion: don't install illuminated/db-profiler 5.5.1
		- Conclusion: don't install laravel/framework v5.6.3
		- Conclusion: don't install laravel/framework v5.6.2
		- Installation request for illuminated/db-profiler ^5.5 -> satisfiable by illuminated/db-profiler[5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4].
		- Conclusion: don't install laravel/framework v5.6.1
		- illuminated/db-profiler 5.5.0 requires illuminate/database 5.5.* -> satisfiable by laravel/framework[v5.5.34], illuminate/database[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
		- Can only install one of: laravel/framework[v5.6.0, v5.5.34].
		- don't install illuminate/database v5.5.0|don't install laravel/framework v5.6.0
		- don't install illuminate/database v5.5.16|don't install laravel/framework v5.6.0
		- don't install illuminate/database v5.5.17|don't install laravel/framework v5.6.0
		- don't install illuminate/database v5.5.2|don't install laravel/framework v5.6.0
		- don't install illuminate/database v5.5.28|don't install laravel/framework v5.6.0
		- don't install illuminate/database v5.5.33|don't install laravel/framework v5.6.0
		- don't install illuminate/database v5.5.34|don't install laravel/framework v5.6.0
		- Installation request for laravel/framework 5.6.* -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3].

**Comment by dmitry-ivanov** [comment]
Yep, released 5.6.0.

Fix your composer.json to use `5.6.*` version:
"illuminated/db-profiler": "5.6.*"
