### ISSUE TITLE
Can I use this while running phpunit tests and how? Can you demo a gif also?

### ISSUE THREAD

**Issue by ajcastro** [dmitry-ivanov/laravel-db-profiler#2]

**Comment by dmitry-ivanov** [comment]
Hi, @ajcastro !

Yes, you can.

You need two things for that:

1) Force `db-profiler` to run on your testing environment.

You can do it by setting `db-profiler.force` config variable to `true`.
https://laravel.com/docs/5.6/configuration#environment-configuration

PS: So, you can create `config/db-profiler.php`:
```
<?php

return [

    'force' => env('DB_PROFILER', false),

];
```

And then, in your `phpunit.xml` set among others:
```
<env name="DB_PROFILER" value="true"/>
```

Or, also, you can use `.env.testing` file.

2) Add `-vvv` to your run tests command. For example:
```
phpunit --filter your_test_name_here -vvv
```

Have a great day!
