### ISSUE TITLE
Change the name of parameter. It became optional 

### ISSUE THREAD

**Issue by mknparreira** [dmitry-ivanov/laravel-db-profiler#4]
I Would like to change the name of the variable, for instance: change vvv to debug. My idea would be put name on config file.

**Comment by dmitry-ivanov** [comment]
I think `vvv` is okay, it's kinda the highest level of verbosity for many tools, e.g.:

https://stackoverflow.com/questions/24402473/what-is-meaning-of-vvv-option-in-curl-request
