### ISSUE TITLE
Add support Laravel 6.0

### ISSUE THREAD

**Issue by mustorze** [dmitry-ivanov/laravel-db-profiler#6]
As Laravel 6.0 has been released, it would be nice to add support for that. xD

**Comment by dmitry-ivanov** [comment]
Yep, I'll be working on that asap 🙂 Thanks! 🙂

**Comment by dmitry-ivanov** [comment]
Laravel 6 support added, see release [`6.0.0`](https://github.com/dmitry-ivanov/laravel-db-profiler/releases/tag/6.0.0).

Thanks! 🙂
