### ISSUE TITLE
Support 8.13

### ISSUE THREAD

**Issue by mxsxs2** [dmitry-ivanov/laravel-db-profiler#8]
I receive the following error message from composer when I try to install db-profiler with Laravel 8.13:

```
 - Root composer.json requires illuminated/db-profiler ^7.0 -> satisfiable by illuminated/db-profiler[7.0.0, 7.x-dev].
    - illuminated/db-profiler 7.x-dev requires illuminate/support ^7.0 -> satisfiable by illuminate/support[v7.0.0, ..., 7.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.6.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
```

**Comment by dmitry-ivanov** [comment]
You have to use the proper version of the package (`^8.0`) with Laravel 8:

![dmitry-ivanov_laravel-db-profiler__Database_Profiler_for_Laravel_Web_and_Console_Applications_](https://user-images.githubusercontent.com/1286821/98273133-94fd8780-1f9a-11eb-852e-72530aaab850.png)
