### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by sniperwolf** [dmitry-ivanov/laravel-db-profiler#9]
Reading the composer requirements, `laravel-db-profiler` does not support PHP 8. Is there a plan to support it?

Thanks

**Comment by dmitry-ivanov** [comment]
Hi, @sniperwolf ! Yep, I'll add PHP8 support soon 👍

**Comment by dmitry-ivanov** [comment]
@sniperwolf PHP8 support has been added for `6.x`, `7.x` and `8.x` 👍
